#! /bin/bash

#####################################################################################
function info () { echo -e "\033[1;32m$@\033[0m"; }
function warn () { echo -e "\033[1;33m$@\033[0m"; }
function die  () { echo -e "\033[0;31m$*\033[0m"; exit 1; }
#####################################################################################

export PODMAN_IMAGE='linux-build-wrynose'
export PODMAN_USER=ubuntu
export PODMAN_UUID=$(id -u)
export PODMAN_UGID=$(id -g)
export PODMAN_WORKDIR=$(pwd)
export PODMAN_MOUNT="/home/${PODMAN_USER}/workspace"
export PODMAN_PARAMS="--rm --userns=keep-id --user ${PODMAN_USER} -v ${PODMAN_WORKDIR}:${PODMAN_MOUNT} ${PODMAN_IMAGE}"

export PATH="${PODMAN_WORKDIR}/:${PATH}"
#####################################################################################

# find podman image and create if missing
podman build --build-arg "DOCKER_UID=${PODMAN_UUID}" --build-arg "DOCKER_GID=${PODMAN_UGID}" --build-arg "DOCKER_USER=${PODMAN_USER}" -t ${PODMAN_IMAGE} -f docker/Dockerfile docker

#####################################################################################

# run podman with interactive shell and mounted local folder
function bb.shell() {
	podman run -it ${PODMAN_PARAMS} /bin/bash -l
}

export -f bb.shell

#####################################################################################

SUBMODULES="$(cat <<-EOF
0ad6c1c34a5e07a5f8dd66ab248c1e7b37b69fa9,layers/bitbake
ef022bf82d79015802309d14c28b13373ebe53f5,layers/openembedded-core
6bf0d8ad57b33950bab4c7f6c037e1ccb6f6e2eb,layers/meta-openembedded
5ccbca8001083487844a244f9b616022a21215d4,layers/meta-openrc
f62c67921474370829d24a4fa01ef88543f3906b,layers/meta-raspberrypi
EOF
)"

#####################################################################################

function init_submodules() {
	git submodule init
	git submodule update --recursive
}

#####################################################################################

function reset_submodules() {
	for submodule in ${SUBMODULES}; do
		IFS=',' read revision location <<< "${submodule}"
		info "RESET ${location} to REVISION ${revision}"

		pushd ${location} > /dev/null
			git clean -fxd ./    
			git reset --hard HEAD
			git checkout ${revision}
			
			local layer_patch=../${location#layers/}.patch
			[ -f ${layer_patch} ] && git apply ${layer_patch}
		popd > /dev/null
	done
}

#####################################################################################

init_submodules
reset_submodules

#####################################################################################
