# enable color support of ls and also add handy aliases
alias ls='ls --color=auto --human-readable --file-type '
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'

PS1='[\u@\[\033[01;33m\]\H\[\033[00m\] \[\033[01;34m\]\W\[\033[00m\]\[\033[32m\] [docker]\[\033[00m\]]\$ '

# --- Neo-PiOS bitbake aliases (available at login via ~/.bashrc) ---
BB_COMMAND="bitbake"
alias bb=${BB_COMMAND}
alias bb.clean="bitbake -c clean -c cleansstate"
alias bb.edit="devtool modify"
alias bb.apply="devtool update-recipe -a ../layers/meta-neopios"
alias bb.close="devtool reset"
alias bb.shell="bitbake -c devshell"
alias bb.linux="bitbake linux -c"
alias bb.sysroot="bitbake -c build_target_sysroot build-sysroots"
alias bb.sdk="bitbake -c populate_sdk"


