require include/neopios.inc

DISTRO = "neopios"
DISTRO_NAME = "Neo-PiOS"
DISTRO_VERSION = "26.08"

SDK_VENDOR = "-neopios"
SDK_VERSION = "Neo-PiOS-SDK-${DISTRO_VERSION}"

MAINTAINER = "Neo-PiOS <asiminciuc@yahoo.com>"

DISTRO_FEATURES:append = " opengl wayland pam wifi vulkan"

# wrynose auto-adds these defaults; opt out to keep build scope close to nanbield
DISTRO_FEATURES_OPTED_OUT:append = " ptest multiarch x11 pcmcia 3g"

INIT_MANAGER = "openrc"
